### PR TITLE
Quality of life improvements for API

### PR DESCRIPTION
**Pull request by DennisCorvers**
- Add the ability to use offsets for managed buffers so that no unsafe code is required on the managed end for receiving/sending at an offset.
- Add the ability to toggle on/off blocking mode rather than just on.

### CODE REVIEW

**Comment by nxrighthere** [comment]
Feel free to modify `nanosockets_set_nonblocking()` function instead of adding a new one, just make `shouldBlock` parameter optional and set it to `false` by default.

**Comment by DennisCorvers** [comment]
> Feel free to modify `nanosockets_set_nonblocking()` function instead of adding a new one, just make `shouldBlock` parameter optional and set it to `true` by default.

Default set to `false` to keep the API compatible with previous versions, so that a default call to `SetNonBlocking` results in a non-blocked socket.

**Comment by nxrighthere** [comment]
Thanks!

**Comment by DennisCorvers** [comment]
Would it be possible for you to release the latest binaries? I currently do not have the tools installed/configured to build the native libraries. Thanks

**Comment by nxrighthere** [comment]
Done.

**Pull request merged**
